#!/bin/bash

if [ ${#} -ne 2 ]; then
  echo "Usage Error: too many arguments" >&2
  exit 1
fi

for word in $(cat $1); do
  if [ ! -f $word.args ]; then
    if [ ! -f $word.in ]; then
      $2 > $word.out
    else 
      $2 < $word.in > $word.out
    fi
  else 
    if [ ! -f $word.in ]; then
      $2 $(cat $word.args) > $word.out
    else 
      $2 $(cat $word.args) < $word.in > $word.out
    fi
  fi
done
