#!/bin/bash

if [ ${#} -ne 2 ]; then
  echo "Usage Error: too many arguments" >&2
  exit 1
fi

for word in $(cat $1); do
  if [ ! -f $word.out ]; then
    echo "Error: missing expected readable file" >&2
   exit 1
  fi
done

for word in $(cat $1); do
  tmp1=$(mktemp)
  if [ ! -f $word.args ]; then
    if [ ! -f $word.in ]; then
      $2 > $tmp1
      diff $tmp1 $word.out > /dev/null
      if [ $? -eq 0 ]; then
        echo "do nothing" > /dev/null
      else 
        echo "Test failed: $word"
        echo "Args:"
        echo "Input:"
        echo "Expected:"
        cat $word.out
        echo "Actual:"
        cat $tmp1
      fi
    else 
      $2 < $word.in > $tmp1
      diff $tmp1 $word.out > /dev/null
      if [ $? -eq 0 ]; then
        echo "do nothing" > /dev/null
      else 
        echo "Test failed: $word"
        echo "Args:"
        echo "Input:"
        cat $word.in
        echo "Expected:"
        cat $word.out
        echo "Actual:"
        cat $tmp1
      fi
    fi
  else 
    if [ ! -f $word.in ]; then
      $2 $(cat $word.args) > $tmp1
      diff $tmp1 $word.out > /dev/null
      if [ $? -eq 0 ]; then
        echo "do nothing" > /dev/null
      else 
        echo "Test failed: $word"
        echo "Args:"
        cat $word.args
        echo "Input:"
        echo "Expected:"
        cat $word.out
        echo "Actual:"
        cat $tmp1
      fi
    else 
      $2 $(cat $word.args) < $word.in > $tmp1
      diff $tmp1 $word.out > /dev/null
      if [ $? -eq 0 ]; then
        echo "do nothing" > /dev/null
      else 
        echo "Test failed: $word"
        echo "Args:"
        cat $word.args
        echo "Input:"
        cat $word.in
        echo "Expected:"
        cat $word.out
        echo "Actual:"
        cat $tmp1
      fi
    fi
  fi
  rm $tmp1
done    
